mappings:
  dynamic: strict
  properties:
    id:
      type: text
    title:
      type: text
    image:
      type: text
    released_at:
      type: text
    isbns:
      type: text
    author:
      type: object
      properties:
        id:
          type: text
        name:
          type: text
    summary:
      type: object
      properties:
        fr:
          type: text
