mappings:
  dynamic: strict
  properties:
    id:
      type: text
    name:
      type: text
    books:
      type: object
      properties:
        id:
          type: text
        name:
          type: text
    authors:
      type: object
      properties:
        id:
          type: text
        name:
          type: text
